### ISSUE TITLE
How to prepare the dataset

### ISSUE THREAD

**Issue by Plovor** [ISCS-ZJU/iCache#1]
Hi! I am trying to run the project on my own linux server. I downloaded the cifar10 dataset by torchvision and extracted it to `~/dataset/cifar10`, and then modified the dcserver.yaml 

> `dcserver_data_path: "/home/xxx/dataset/cifar10/train"`

However the training script failed to fetch the dataset, and the dataloader worker put `ExceptionWrapper` to the data_queue.
I have already run the `etcd` and `dcsever.go` programs according to README, and they have been successfully launched. 

I think this may be related to `etcd`, but I don't know how to solve it. Looking forward to your early reply.

**Comment by Plovor** [comment]
I've resolved this issue in a single-node environment by setting `curaddr = 127.0.0.1` in files `rpc.go` and `distkv.go`. 
The problem may be related to the server's firewall.

**Comment by Wangzesonga** [comment]
> cifar10

Hi Plovor, which type of CIFAR-10 dataset did you download? 

I'm not familiar with this dataset. Could you describe the file hierarchy under the dataset/cifar10/train directory? 

When I ran cached_image_classification.py, I encountered the following error: "RuntimeError: Found 0 files in subfolders of: /home/xxx/dataset/cifar10/train. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp."

Thank you !

**Comment by Plovor** [comment]
@Wangzesonga Try this: https://github.com/R-I-S-Khan/SHADE/blob/main/benchmarks/prepare_CIFAR10.py

**Comment by Wangzesonga** [comment]
> @Wangzesonga Try this: https://github.com/R-I-S-Khan/SHADE/blob/main/benchmarks/prepare_CIFAR10.py

It works, thank you !
